"""Generate search files from individually reviewed assets (standard library only)."""
import argparse
import hashlib
import json
from pathlib import Path
from urllib.parse import quote, urlsplit
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'scripts/search-selection.json'
SM = 'http://www.sitemaps.org/schemas/sitemap/0.9'
IM = 'http://www.google.com/schemas/sitemap-image/1.1'


def render(config):
    base = config['site_url']
    parsed = urlsplit(base)
    if parsed.scheme != 'https' or not parsed.netloc or not base.endswith('/') or parsed.query or parsed.fragment:
        raise ValueError('site_url must be an absolute HTTPS URL ending in /')
    catalog = json.loads((ROOT / 'assets/data/projects.json').read_text(encoding='utf-8'))
    displayed = {m['src'] for p in catalog for m in p['media'] if m['type'] == 'image'}
    approved = config['approved']
    paths = set()
    for item in approved:
        path = item['path']
        local = (ROOT / path).resolve()
        if not local.is_relative_to(ROOT) or path in paths:
            raise ValueError(f'Unsafe or duplicate path: {path}')
        if not item.get('reason') or hashlib.sha256(local.read_bytes()).hexdigest() != item['sha256']:
            raise ValueError(f'Asset changed or missing review; inspect it again before approving: {path}')
        if item['kind'] == 'image' and path not in displayed:
            raise ValueError(f'Sitemap image must appear in the portfolio: {path}')
        if item['kind'] not in ('image', 'document'):
            raise ValueError(f'Unsupported asset kind: {item["kind"]}')
        paths.add(path)

    ET.register_namespace('', SM)
    ET.register_namespace('image', IM)
    sitemap = ET.Element(f'{{{SM}}}urlset')
    home = ET.SubElement(sitemap, f'{{{SM}}}url')
    ET.SubElement(home, f'{{{SM}}}loc').text = base
    for item in approved:
        url = base + quote(item['path'], safe='/')
        if item['kind'] == 'image':
            node = ET.SubElement(home, f'{{{IM}}}image')
            ET.SubElement(node, f'{{{IM}}}loc').text = url
        else:
            node = ET.SubElement(sitemap, f'{{{SM}}}url')
            ET.SubElement(node, f'{{{SM}}}loc').text = url
    ET.indent(sitemap, space='  ')
    xml = ET.tostring(sitemap, encoding='utf-8', xml_declaration=True).decode() + '\n'

    # Apply only to this portfolio's path; do not restrict unrelated project sites.
    prefix = parsed.path
    rules = [
        '# Generated by python scripts/build_search.py; edit scripts/search-selection.json.',
        '# MUST be served at ' + f'{parsed.scheme}://{parsed.netloc}/robots.txt',
        '# A robots.txt inside a project subdirectory is ignored by crawlers.',
        '# These rules restrict this portfolio only. Merge with any existing host rules.',
        '# Voluntary crawling policy, not access control or a guarantee against AI use.',
        '', 'User-agent: *', f'Disallow: {prefix}', '',
        '# Explicit AI product controls; unknown crawlers are covered above.',
        'User-agent: Google-Extended', 'User-agent: Google-CloudVertexBot',
        f'Disallow: {prefix}', '',
        '# Verified search and LinkedIn preview tokens; not a recruiter-search guarantee.',
    ]
    for agent in config['allowed_agents']:
        if not agent or any(c in agent for c in '\r\n:#* '):
            raise ValueError('Invalid crawler token')
        rules.append(f'User-agent: {agent}')
    rules.append(f'Disallow: {prefix}')
    allowed = ['', 'index.html', 'assets/css/styles.css', 'assets/js/script.js', 'sitemap.xml'] + sorted(paths)
    for path in allowed:
        # $ prevents a filename prefix from also allowing backups or descendants.
        rules.append(f'Allow: {prefix}{quote(path, safe="/")}$')
    rules.extend(['', f'Sitemap: {base}sitemap.xml', ''])
    return {'sitemap.xml': xml, 'robots.txt': '\n'.join(rules)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='verify review hashes and generated files without writing')
    args = parser.parse_args()
    outputs = render(json.loads(MANIFEST.read_text(encoding='utf-8')))
    for name, content in outputs.items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'{name} is stale; run python scripts/build_search.py')
        else:
            path.write_text(content, encoding='utf-8', newline='\n')
    print('PASS: reviewed asset hashes, catalog references, sitemap.xml and robots.txt.' if args.check else 'Built sitemap.xml and robots.txt.')


if __name__ == '__main__':
    main()
